const constants = {
    DATE_FORMAT: "DD-MM-YYYY",
    COMMAND_INDEX: 0,
    SUBSCRIPTION_CATEGORY_INDEX: 1,
    SUBSCRIPTION_START_DATE_INDEX: 1,
    PLAN_NAME_INDEX: 2,
    DAYS_BEFORE_RENEWAL: 10,
    NOT_FOUND_ERROR_CODE: 404,
    UNAUTHORIZED_ERROR_CODE: 401
}

module.exports = constants;