const exceptionStringMapper = {
    INVALID_DATE: "INVALID_DATE",
    DUPLICATE_SUBSCRIPTION_CATEGORY: "ADD_SUBSCRIPTION_FAILED DUPLICATE_SUBSCRIPTION_CATEGORY",
    ADD_TOPUP_FAILED_NO_SUBSCRIPTION: "ADD_TOPUP_FAILED SUBSCRIPTIONS_NOT_FOUND",
    ADD_TOPUP_FAILED_DUPLICATE_TOPUP: "ADD_TOPUP_FAILED_DUPLICATE_TOPUP",
    SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTIONS_NOT_FOUND",
    COMMAND_NOT_FOUND: "COMMAND_NOT_PROVIDED",
    INVALID_PLAN_VIDEO: "INVALID_PLAN_FOR_VIDEO",
    INVALID_PLAN_PODCAST: "INVALID_PLAN_FOR_PODCAST",
    INVALID_PLAN_MUSIC: "INVALID_PLAN_FOR_MUSIC",
    INVALID_PLAN_TOPUP: "INVALID_PLAN_FOR_TOPUP"
}

module.exports = exceptionStringMapper;